// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Phonebook.Infrastructure;

namespace Phonebook.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210909133212_Seed Data")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Phonebook.Domain.Models.Contact", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = "7083b04d-0808-4f75-ba71-e2d61a98bb40",
                            Email = "folakealabi@gmail.com",
                            FirstName = "Folake",
                            ImageUrl = "https://res.cloudinary.com/techtheriac/image/upload/v1629663368/Products/hats/baseballyellow/other-03_yw2jht.jpg",
                            LastName = "Alabi",
                            Phone = "09045689909"
                        },
                        new
                        {
                            Id = "a0767586-aaa7-4045-bef3-3a20c94c56dc",
                            Email = "jamesariyo@gmail.com",
                            FirstName = "James",
                            ImageUrl = "https://res.cloudinary.com/techtheriac/image/upload/v1629663368/Products/hats/baseballyellow/other-03_yw2jht.jpg",
                            LastName = "Ariyo",
                            Phone = "09078976654"
                        },
                        new
                        {
                            Id = "0d477abb-d999-4911-8efb-ddde949685e6",
                            Email = "kolaqalagbo@gmail.com",
                            FirstName = "Kolaq",
                            ImageUrl = "https://res.cloudinary.com/techtheriac/image/upload/v1629663368/Products/hats/baseballyellow/other-03_yw2jht.jpg",
                            LastName = "Alagbo",
                            Phone = "09045689978"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
